# Generated by Django 2.1.2 on 2018-10-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstview',
            name='movie',
        ),
        migrations.DeleteModel(
            name='firstview',
        ),
    ]
