# Generated by Django 2.1.2 on 2018-12-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_movie_last_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('watch_for', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
