# Generated by Django 2.1.2 on 2018-12-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20181208_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='initial_review',
            new_name='InitialReview',
        ),
    ]
