# Generated by Django 2.1.2 on 2018-12-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20181208_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewatchReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('discovery', models.CharField(max_length=200)),
                ('new_rating', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='initialreview',
            old_name='rating',
            new_name='initial_rating',
        ),
    ]
