# Generated by Django 2.1.2 on 2018-12-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20181210_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialreview',
            old_name='initial_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rewatchreview',
            old_name='new_rating',
            new_name='rating',
        ),
    ]
