# Generated by Django 2.1.2 on 2018-12-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20181210_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last reviewed'),
        ),
    ]
